name: CI
on:
  push:
    branches: [ main ]

# Cancel previous CI runs
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true # If this is enabled it will cancel current running and start latest

jobs:
  build-ci-image:
    runs-on: ubuntu-latest

    concurrency:
      group: build-ci-image-first
      cancel-in-progress: true # If this is enabled it will cancel current running and start latest

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.38.0

      - name: Build and Push CI image
        run: just docker-push

  main:
    runs-on: ubuntu-latest

    concurrency:
      group: build-ci-image-first
      cancel-in-progress: false # Don't cancel b/c it's the job building the image

    defaults:
      run:
        shell: bash
        working-directory: ./

    container:
      image: coltonmccurdy/gossip:latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4

      - name: lint
        run: just lint

      - name: test
        run: just test

      - name: maelstrom-test-echo
        run: just maelstrom-run echo

      - name: maelstrom-test-unique
        run: just maelstrom-run unique

      - name: maelstrom-test-broadcast
        run: just maelstrom-run broadcast

      - name: maelstrom-test-counter
        run: just maelstrom-run counter

